m9sweeper/m9sweeper

docs/config.toml
docs/layouts/partials/hooks/body-end.html

Adding in multiple versions for documentation. This creates the Releases Navbar dropdown, then dynamically adds in the different versions.

Docs versioning

---

docs/layouts/partials/hooks/body-end.html

The script was naming the "a" html text element to the folder name. Refactored to replace dashes with a period, and inserting v before the version. (e.g v1.1.1)

Changed the text field for versions from folder name to vX.X.X

---

manifests/charts/dash/values.yaml

Add the GitHub ghcr.io and the Kubernetes registry.k8s.io container registries to the defaults in the helm chart.

Add GitHub and Kubernetes container registries to defaults

---

dash/frontend/src/app/modules/private/pages/falco/falco-dialog/falco-dialog.component.html
manifests/charts/m9sweeper/values.yaml

Updates the command shown to users to install m9sweeper to fix the http output URL. Also changes the baseUrl in the main chart to include the full namespace so falco can access it since its installed in a different namespace if not using an ingress.

Update falco output URL and baseUrl default

---

dash/backend/src/modules/docker-registries/services/docker-registries.service.ts

Where the docker registries were previously calling delete on the sensitive properties of docker registries, I replaced it with using a function that does the same.
This makes it so that we can more easily ensure the correct fields are being deleted in every instance this is needed.

Break docker registry sensitive information removal into function

---

dash/frontend/src/app/modules/private/pages/cluster/cluster-info/cluster-info.component.ts
dash/frontend/src/app/modules/private/pages/cluster/cluster-list/cluster-list.component.ts
dash/frontend/src/app/modules/private/pages/dashboard/dashboard.component.ts

Root cause: Having 'height: auto' on the dialog with responsive content caused a deadlock.
Quick summary: the 'height auto' made the dialog want to grow to the size of the content, but the content wanted o grow based on the size of the dialog. This causes the container to grow to a size where it doesn't need to scroll (but isn't fully visible on the screen).
Solution: set the dialog height to 75% (with a min height for small devices), Causing it to be a more reasonable size, and will now scroll if needed.

Cluster wizard now scrolls

---

dash/backend/src/modules/policy/controllers/policy.controller.ts
dash/frontend/src/app/modules/private/pages/exceptions/exception-create/exception-create.component.ts

The validation had the altSeverity field on the exception create/edit field marked as required. This made users unable to submit gatekeeper & policy exceptions since that field is only visible on the override exception form.
Solution: subscribed to value changes for the type field, and change the validators on the altSeverity field accordingly.
The error was caused because they attempted to add the metadata object to the policy without checking if it had been created or not.
Solution: moved that line to within the if statement checking for its existence.
Also changed the status code for the policy name already existing from 500 to 409 (Conflict)

A couple small bug fixes

---

dash/backend/.env.sample
dash/backend/src/modules/command-line/services/exception-block.service.ts
dash/backend/src/modules/exceptions/dao/exceptions.dao.ts

the calculateExceptionBlock function in the exceptionBlockService builds the body of a rego array.
When their are no image-specific exceptions, it defaults to adding '{true, true}'. Unlike the similar logic for non-image specific exceptions, there is no comma after this {true, true}.
If an exception hits this case, and has at least one more exception processed after it, this will cause a rego syntax error.
Works by coincidence if this kind of exception was the only exception or the exception applied last, as then that comma would be optional. (having it for the last doesn't matter as trailing commas are legal in rego)
When getting the gatekeeper exceptions, exceptions were being filtered to only include ones whose issue_identifier was an empty string. However, new gatekeeper exceptions …

Fix for Gatekeeper sync issue 

---

dash/frontend/src/app/modules/private/pages/cluster/cluster-edit/cluster-edit.component.html
dash/frontend/src/app/modules/private/pages/docker-registries/docker-registries-create/docker-registries-create.component.html
dash/frontend/src/app/modules/private/pages/exceptions/exception-create/exception-create.component.ts
dash/frontend/src/app/modules/private/pages/exceptions/exception-details/exception-details.component.html
dash/frontend/src/app/modules/private/pages/falco/falco-rule-add-edit-dialog/falco-rule-add-edit-dialog.component.html
dash/frontend/src/app/modules/private/pages/falco/falco-rules-cluster-list/falco-rules-cluster-list.component.html
dash/frontend/src/app/modules/private/pages/falco/falco-rules-cluster-list/falco-rules-cluster-list.component.scss
dash/frontend/src/app/modules/private/pages/falco/falco-settings/falco-settings.component.html
dash/frontend/src/app/modules/private/pages/falco/falco-settings/falco-settings.component.scss
dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.html
dash/frontend/src/styles.scss

Fixes for:
- appearance="standard" no longer allowed on form fields, removed where applicable
- exception create component attempted to reference undefined gateKeeperList variable. Now initializes to observeable of empty array
- mat-chip-grid is now only allowed withint form controls. Replace usages outside of forms with mat-chip-lists
- Removed redundant mat-button decorator from a button, as now having duplicate mat-X-button decorators throws errors
- Cleaned up Falco Settings page, as the upgrades caused it to look strange. Did end up changing the aesthetics to be more in line with MAterial design principals, ass the original design would be very difficult to replicate using Angular Material. Image attached of new layout

Angular Upgrade follow up

---

dash/backend/src/modules/reports/controllers/reports.controller.ts
dash/backend/src/modules/reports/dao/reports.dao.ts
dash/backend/src/modules/reports/services/reports.service.ts
dash/frontend/src/app/app.component.scss
dash/frontend/src/app/core/services/reports.service.ts
dash/frontend/src/app/modules/private/pages/api-key-management/api-key-list/api-key-list.component.html
dash/frontend/src/app/modules/private/pages/api-key-management/api-key-list/api-key-list.component.scss
dash/frontend/src/app/modules/private/pages/docker-registries/docker-registries-list/docker-registries-list.component.scss
dash/frontend/src/app/modules/private/pages/exceptions/exception-list/exception-list.component.scss
dash/frontend/src/app/modules/private/pages/external-auth-configuration/external-auth-configuration-list/external-auth-configuration-list.component.scss
dash/frontend/src/app/modules/private/pages/falco/falco-events-list/falco-events-list.component.html
dash/frontend/src/app/modules/private/pages/falco/falco-events-list/falco-events-list.component.scss
dash/frontend/src/app/modules/private/pages/falco/falco-events-list/falco-events-list.component.ts
dash/frontend/src/app/modules/private/pages/policies/policy-list/policy-list.component.scss
dash/frontend/src/app/modules/private/pages/reports/reports-list/reports.component.html
dash/frontend/src/app/modules/private/pages/reports/reports-list/reports.component.scss
dash/frontend/src/app/modules/private/pages/reports/running-vulnerabilities/running-vulnerabilities.component.html
dash/frontend/src/app/modules/private/pages/reports/running-vulnerabilities/running-vulnerabilities.component.scss
dash/frontend/src/app/modules/private/pages/reports/running-vulnerabilities/running-vulnerabilities.component.ts
dash/frontend/src/app/modules/private/pages/user/user-list/user-list.component.scss
dash/frontend/src/styles.scss

- Falco page: use global table styling
- Running Vulnerabilities report:
- use global table styling
- add pagniation (adds it as an option for the backend as well - defaults to 0 and only uses it if limits is also set)
- set min-width for table columns so they're legible on small screen
- adjust formatting on the list of available reports
- Org Settings pages: make table content scrollable

Bug Fixes #2

---

dash/backend/scripts/proxy-webhook/README.md
docs/content/en/docs/Getting started/advanced-install.md
docs/content/en/docs/Getting started/easy-install.md

Updates the documentation to show that it is for more than just AKS and adds alerts to some sections to refer to the Validating Webhook Proxy section in the docs for more information.

Update Validating Webhook proxy documentation

---

dash/frontend/src/app/modules/private/pages/cluster/cluster-list/cluster-list.component.scss
dash/frontend/src/app/modules/private/pages/cluster/cluster-list/cluster-list.component.ts
dash/frontend/src/app/modules/private/pages/cluster/cluster-summary/cluster-summary.component.html
dash/frontend/src/app/modules/private/pages/cluster/cluster-summary/cluster-summary.component.scss
dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.html
dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.scss
dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.ts
dash/frontend/src/app/modules/private/pages/image/images-list/image.component.html
dash/frontend/src/app/modules/private/pages/image/images-list/image.component.scss
dash/frontend/src/styles.scss

- Image Scan Results page
- Use standard mat components (mat-table, mat-card)
- Use row & column classes for headers (page & card)
- Image List page
- Line up card with page header
- Use row & column classes for page header
- Align button text
- Resize table columns (set min- & max-widths)
- Pull off some unnecessary styling
- Cluster List dash:
- set reasonable initial chart sized

Images Pages Re-Formatting

---

dash/frontend/src/app/modules/private/pages/cluster/kube-bench/kube-bench-report-details/kube-bench-report-details.component.html
dash/frontend/src/app/modules/private/pages/cluster/kube-bench/kube-bench-report-details/kube-bench-report-details.component.scss
dash/frontend/src/app/modules/private/pages/cluster/kube-bench/kube-bench-report-details/kube-bench-report-details.component.ts
dash/frontend/src/styles.scss

This used to be a mat-table with a hand-coded "dropdown" intended to work like an accordion.
Now it's a bunch of nested accordions filled with the correct contents.
_(note that none of the elements are scrollable)_
Desktop:
Mobile:
Desktop:
Mobile:

Kube Bench Test Results Cleanup

---

dash/frontend/src/app/modules/private/pages/cluster/cluster-list/cluster-list.component.html
dash/frontend/src/app/modules/private/pages/cluster/cluster-list/cluster-list.component.scss
dash/frontend/src/app/modules/shared/side-nav/side-nav.component.html
dash/frontend/src/app/modules/shared/side-nav/side-nav.component.scss
dash/frontend/src/generic-styles.scss
dash/frontend/src/styles.scss

This PR includes a new file titled `generic-styles.scss`.
It uses the media queries from flexboxgrid (which is what we use for existing flexbox layout classes) and the conventions defined by Bootstrap to allow us to create classes to apply styling by size.
This SHOULD NOT be used for element-specific styling or program styling. It is ONLY for generic classes like the ones currently included.
Examples of potential additions:
- mx-xs-3: apply 1em margins to the left and right of an element to all sizes equal to or greater than xs
- mb-md-2: apply 0.5em margins to the bottom of an element to all sizes equal to or greater than md (medium)

UI Cleanup Tasks

---

dash/backend/src/modules/cluster/dao/cluster.dao.ts

Cause:
The logger service inside the function passed to the knex transaction didn't have 'this' in scope. Was previously not an issue because they were changed to use the logger service in a recent clean up.
Solution
Instead of using the 'function() {...}' syntax for the function passed in, use the '() => {...}' syntax as it preserves the context, and thus allows this.logger to be defined.

fix init job

---

dash/backend/src/modules/k8s-image/services/k8s-image.service.ts

Cause:
Was using existingImageDto.id rather than savedImaged.id when the sync job was trying to update a new image. Since this was in a code block only reachable if we didn't have existingImageDto, that was guaranteed to error out.

fix cluster sync job

---

dash/frontend/src/app/modules/private/pages/api-key-management/api-key-list/api-key-list.component.html
dash/frontend/src/app/modules/private/pages/cluster/gate-keeper/gate-keeper.component.html
dash/frontend/src/app/modules/private/pages/external-auth-configuration/external-auth-configuration-list/external-auth-configuration-list.component.html
dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.html
dash/frontend/src/app/modules/private/pages/policies/policy-create/policy-create.component.html
dash/frontend/src/app/modules/shared/components/readonly-checkbox/readonly-checkbox.component.html
dash/frontend/src/app/modules/shared/components/readonly-checkbox/readonly-checkbox.component.scss
dash/frontend/src/app/modules/shared/components/readonly-checkbox/readonly-checkbox.component.ts
dash/frontend/src/app/modules/shared/shared.module.ts

Created a shared readonly checkbox component and implemented in all the spots I could find that should have a readonly checkbox:
- image scan results page - compliant & fixable columns
- api key list active column
- gatekeeper template list enforced column
- auth config list enabled column
- policy add/edit scanner table required & active columns
ticket 6834

implement readonly checkbox component

---

dash/backend/package-lock.json
dash/backend/package.json
dash/backend/src/modules/kube-hunter/dao/kube-hunter.dao.ts
dash/backend/src/modules/kube-hunter/service/kube-hunter.service.ts
dash/frontend/src/app/modules/private/pages/cluster/kube-hunter/kube-hunter-dialog/kube-hunter-dialog.component.html
dash/frontend/src/app/modules/private/pages/cluster/kube-hunter/kube-hunter-dialog/kube-hunter-dialog.component.ts
dash/frontend/src/app/modules/private/pages/cluster/kube-hunter/kube-hunter.component.html
dash/frontend/src/app/modules/private/pages/cluster/kube-hunter/kube-hunter.component.ts
dash/frontend/src/app/modules/shared/components/copy-to-clipboard-button/copy-to-clipboard-button.component.html
dash/frontend/src/app/modules/shared/components/copy-to-clipboard-button/copy-to-clipboard-button.component.ts
dash/frontend/src/styles.scss

- Now says 'Not yet run' as pen test status, has N/A for vulnerability counts, and 'Run kube-hunter to audit your cluster security' as Our advice when no kube-hunter scan has been run for the cluster.
- Neatened up some of the kube hunter page logic
- Fixed bug where the kube hunter report pagination was based on the total number of reports for all clusters rather than just the current cluster
- Neatened spacing for copy to clipboard button
- Removed @types/cron package - It was causing build errors and since we don't have the main cron package is not doing anything
- Added a responsive mode to the copy to clipboard button where it will turn into an icon button rather than a text button on smaller screens.
Ticket: 6825

Cleanup kube-hunter page for no reports

---

trawler/src/main/java/io/m9sweeper/trawler/ScanRunner.java
trawler/src/main/java/io/m9sweeper/trawler/framework/docker/DockerImage.java
trawler/src/main/java/io/m9sweeper/trawler/scanners/Trivy.java

Changes made:
When the image digest is available, Trawler will use it to ensure the proper image is pulled. If it is not available (or is TMP_xxx) it will pull it by name and function as it previously did.
Image Id has changed... error can no longer happen, as Trawler will now pull the old version.
For exampl: If we have an nginx:latest running in our cluster that is actually nginx:1.20, when scanned, it will pull using the digest, so it will actually scan nginx:1.20 and give the expected result for that scan. With the old behavior, Trawler would pull nginx:latest by name, but would actually get nginx:1.25, and this would result in the Image ID does not match.... error, and no possibility of scanning that older nginx:latest image.

Fix Trawler scanning

---

dash/backend/src/modules/k8s-image/services/k8s-image.service.ts

Now in the function that builds the image url to match what the equivalent function used in the frontends add image button.
Will auto prefix with default docker registry if no docker registry in image name
Will assume the tag is latest if none is provided
Ex. 
nginx -> docker.io/nginx:latest
registry.k8s.io/kube-proxy:v1.27.2 -> registry.k8s.io/kube-proxy:v1.27.2 [same]

Fix cluster sync tagless images

---

.github/workflows/docker-build.yaml
.github/workflows/selenium-test.yaml

Changes the GHCR login steps to use a PAT so that packages can be pushed when running PR checks from a forked repository. Also fixes an issue where the Install m9sweeper step under the selenium tests still happens even if the wait steps for the dash/trawler images produced a failure outcome.

Fix GHCR login and m9sweeper installation when waits failed

---

.github/workflows/forked-pr.yaml
.github/workflows/main.yaml

Since secrets are not shared to workflows triggered by forks, a new workflow is created to run everything without the need to push to the docker registry and thus not need the secrets.

Add workflows for PR's that are from forks

---

.github/workflows/forked-pr.yaml

Modifies the workflow for PR's from forked repositories to export the image as a tar file and then load it into minikube from that tar file.

Fixes docker image not found for minikube image load command

---

manifests/charts/dash/templates/cronjob-exception-status-update.yaml
manifests/charts/dash/templates/cronjob-gatekeeper-exception-block.yaml
manifests/charts/dash/templates/cronjob-scrape-history.yaml
manifests/charts/dash/templates/cronjob-scrape.yaml
manifests/charts/dash/templates/dash-falco.yaml
manifests/charts/dash/templates/deployment.yaml
manifests/charts/dash/templates/job-init.yaml

Update the dash chart to ensure that the pullPolicy for the dash and kubesec images is actually respected and used. This is needed when installing in minikube and images have been manually loaded via the `minikube image load` command since you need to set the imagePullPolicy to `Never` in that situation.

Ensure dash imagePullPolicy is respected

---

selenium-testing/test/specs/cluster/images.spec.ts

Sometimes the images test would fail as 2 minutes was not always long enough for the button to become usable.

Increase timeout for waiting for rescan image button to be usable

---

dash/backend/src/modules/cluster-group/dao/cluster-group-dao.ts
dash/backend/src/modules/cluster/dao/cluster.dao.ts
dash/backend/src/modules/falco/dao/falco.dao.ts
dash/backend/src/modules/pod/controllers/pod.controller.ts
dash/backend/src/modules/pod/dao/pod.dao.ts
dash/backend/src/modules/pod/services/pod.service.ts
dash/backend/src/util/date_util.ts
dash/frontend/src/app/core/services/pod.service.ts
dash/frontend/src/app/modules/private/pages/cluster/cluster-list/cluster-list.component.ts
dash/frontend/src/app/modules/private/pages/cluster/cluster-summary/cluster-summary.component.html
dash/frontend/src/app/modules/private/pages/cluster/cluster-summary/cluster-summary.component.scss
dash/frontend/src/app/modules/private/pages/cluster/cluster-summary/cluster-summary.component.ts
dash/frontend/src/app/modules/private/pages/falco/falco-events-list/falco-events-list.component.ts

The switch for which sort to use was wrapped in an if statement requiring specific sorts. Since there is no default sort, this was effectively preventing it from reaching the default sort case.
Changed it so it always uses the switch statement, and now defaults to date instead of id for default sort.
Also made UI start with date descending selected as the default sort to make this explicit
Changed it from a max-height to a height for its container, so it is now sticky and always takes up the same amount of space on the bottom of the screen.
Also added a loader to the logs to make the infinite scroll more obvious.
2 changes made to solve for dates with no scans looking unscanned:
1. The graph now only includes dates where the cluster/cluster group existed.
a. Effectively this means instead …

Fixes for: falco sort, logs "floating" cluster compliance graph 

---

dash/backend/src/modules/auth/dto/external-auth-config-dto.ts
dash/backend/src/modules/auth/models/auth-configuration.ts
dash/backend/src/modules/auth/services/interfaces/Azure/directory-group.ts
dash/backend/src/modules/auth/services/oauth2/azure-oauth2.service.ts
dash/backend/src/modules/user/services/user-profile.service.ts
dash/frontend/src/app/core/entities/IAuth.ts
dash/frontend/src/app/core/entities/IAuthenticationMethod.ts
dash/frontend/src/app/core/enum/Authority.ts
dash/frontend/src/app/modules/private/pages/external-auth-configuration/external-auth-configuration-create/external-auth-configuration-create.component.html
dash/frontend/src/app/modules/private/pages/external-auth-configuration/external-auth-configuration-create/external-auth-configuration-create.component.scss
dash/frontend/src/app/modules/private/pages/external-auth-configuration/external-auth-configuration-create/external-auth-configuration-create.component.ts
dash/frontend/src/app/modules/public/pages/login/login.component.ts
selenium-testing/package-lock.json
selenium-testing/package.json

Azure OAuth now has 2 extra (optional) fields, and they are configurable in the add/edit sign on method dialog.
the ID of the authority level given to users not assigned an authority level by an AD group. Will be treated as if it was read only if not set.
An array of objects containing an authorityId and a groupId.
If a user is part of an AD group with an ID specified in this array, they are eligible for the associated authority.
When a user signs in for the first time with Azure Auth, they will be created with the appropriate Authority Level based on these mappings. When a used signs in with their already created Azure account, their authority will be checked. If it is different than what it should be, it will be changed.
Either way the rules for determining which authority level is:
1. …

Determine Authority Levels based on AD groups (Ticket 6743)

---

dash/frontend/src/app/modules/private/pages/reports/historical-vulnerabilities/historical-vulnerabilities.component.html
dash/frontend/src/app/modules/private/pages/reports/running-vulnerabilities/running-vulnerabilities.component.html
dash/frontend/src/app/modules/private/pages/reports/vulnerability-difference-by-date/vulnerability-difference-by-date.component.html
dash/frontend/src/app/modules/private/pages/reports/vulnerability-export/vulnerability-export.component.html
dash/frontend/src/app/modules/private/private.component.html
dash/frontend/src/app/modules/shared/side-nav/side-nav.component.html
dash/frontend/src/generic-styles.scss
dash/frontend/src/styles.scss

Print reports:
- add -print- to custom style generation
- add ability to include `!important` in custom style generation (defaults to false)
- hide navigation
- hide "download" buttons
- hide scrollbars in Chrome (+ possibly others - used webkit)

Print Reports Cleanup 1

---

dash/frontend/src/app/modules/private/pages/cluster/add-template-constraint/add-template-constraint.component.html
dash/frontend/src/app/modules/private/pages/cluster/add-template-constraint/add-template-constraint.component.scss
dash/frontend/src/app/modules/private/pages/reports/vulnerability-export/vulnerability-export.component.scss
dash/frontend/src/app/modules/private/pages/user/user-list/user-list.component.scss
dash/frontend/src/styles.scss

- `add-template-constraint.component.html`: fix indentation
- `add-template-constraint.component.scss`: move page-specific style into the page's stylesheet
- `vulnerability-export.component.scss`: adjust title padding for print
- `user-list.component.scss`: remove unnecessary import
- `styles.scss`:
- make `.cluster-dashboard` get the grey background color from the standard palette
- for print:
- make the background color white and remove the box shadowing on the cards
- adjust the page title margin so it aligns with the card titles

Print Reports Cleanup 2

---

dash/backend/src/modules/image/dao/image.dao.ts
dash/backend/src/modules/reports/dao/reports.dao.ts
dash/backend/src/modules/reports/services/reports.service.ts
dash/frontend/src/app/modules/private/pages/reports/vulnerability-difference-by-date/vulnerability-difference-by-date.component.ts

Frontend:
- report page: autofill dates for convenience
Backend:
- `image.dao.ts`: + subquery filtering to speed up graph
- `reports.dao.ts`: rework `getDifferencesInVulnerabilities` method
- `reports.service.ts`: spacing for `getVulnerabilityDifferenceByDate` method

Speed up "Vulnerability Difference by Date" Endpoints

---

dash/backend/src/modules/cluster/dao/cluster.dao.ts
dash/backend/src/modules/gatekeeper/controllers/gatekeeper-constraint-template.controller.ts
dash/backend/src/modules/reports/controllers/reports.controller.ts
dash/frontend/src/app/modules/private/menus/services/cluster-list-menu.service.ts
dash/frontend/src/app/modules/private/menus/services/settings-menu.service.ts
dash/frontend/src/app/modules/private/pages/change-password/change-password.component.html
dash/frontend/src/app/modules/private/pages/cluster/add-edit-constraint-template-manifest/add-edit-constraint-template-manifest.component.html
dash/frontend/src/app/modules/private/pages/cluster/add-edit-constraint-template-manifest/add-edit-constraint-template-manifest.component.ts
dash/frontend/src/app/modules/private/pages/cluster/gate-keeper-details/gate-keeper-details.component.html
dash/frontend/src/app/modules/private/pages/cluster/gate-keeper-details/gate-keeper-details.component.ts
dash/frontend/src/app/modules/private/pages/cluster/gate-keeper/gate-keeper.component.html
dash/frontend/src/app/modules/private/pages/cluster/kube-bench/kube-bench.component.html
dash/frontend/src/app/modules/private/pages/cluster/kube-hunter/kube-hunter.component.html
dash/frontend/src/app/modules/private/pages/exceptions/exception-details/exception-details.component.html
dash/frontend/src/app/modules/private/pages/exceptions/exception-details/exception-details.component.ts
dash/frontend/src/app/modules/private/pages/exceptions/exception-list/exception-list.component.html
dash/frontend/src/app/modules/private/pages/falco/falco-events-list/falco-events-list.component.html
dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.html
dash/frontend/src/app/modules/private/pages/policies/policy-list/policy-list.component.html
dash/frontend/src/app/modules/shared/alert-dialog/alert-dialog.component.ts
dash/frontend/src/app/modules/shared/side-nav/interfaces/menu-content-trigger.interface.ts
dash/frontend/src/app/modules/shared/side-nav/side-nav.component.html
dash/frontend/src/app/modules/shared/side-nav/side-nav.component.ts
dash/frontend/src/app/modules/shared/subnavigation/sub-navigation.component.html
dash/frontend/src/app/modules/shared/subnavigation/sub-navigation.component.ts

- Gatekeeper (All cahnges for RO users)
- Get Constraint Template endpoint made accessible to RO users
- Constraint Details page - Edit button becomes 'View' button for viewing the YML of the template, and opened dialog 
is read only
- Gatekeeper not installed - no longer has install button in recommendation section
- Gate keeper installed with no constraint templates - no longer has add button in recommendations section
- Reports - All endpoints made accessible to RO users
- 'Add Cluster Group' button in side nav no longer visible for RO users
- kube-bench - no longer has 'run audit button' for RO users
- kube-hunter - no longer has 'run audit button' for RO users
- Exceptions Details - edit & delete button no longer visible for RO users
- exceptions list - action column no longer …

Auth audit

---

manifests/charts/dash/templates/deployment.yaml
manifests/charts/trawler/templates/deployment.yaml

There may be certain instances where someone may need to apply specific labels or annotations to the pod or deployment for m9sweeper's dash or trawler. This commit adds that ability to the helm charts.

Add ability to specify extra annotations and labels for dash and trawler

---

manifests/charts/kube-bench/templates/cronjob-eks.yaml

As per CIS Kubernetes Benchmark support for EKS is as below.
https://github.com/aquasecurity/kube-bench/blob/main/docs/platforms.md#cis-kubernetes-benchmark-support
`eks-1` is not valid anymore results in below error, `eks-1.2.0` should fix the issue.
```
error validating targets: No targets configured for eks-1.0
```

Update aws eks benchmarking to `eks-1.2.0` for kube-bench chart

---

dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.html

Revert to original behavior where you can trigger scans of images that are already scanned.
This allows users to trigger new scans of images that get "stuck" if something happens in the scanning flow and nothing gets sent back to dash

can now scan images that are marked as scan_queued

---

dash/backend/src/modules/command-line/commands/helm-setup.command.ts

Would error if Metrics user already existed.

fix to check if Metrics user already exists

---

manifests/charts/dash/templates/validatingwebhookconfiguration.yaml

Will now display a human readable error message if ingress.hosts or ingress.hosts[0] is not set instead of bombing out.

validating webhook requires ingress.hosts

---

docs/content/en/docs/Getting started/advanced-install.md
docs/content/en/docs/Getting started/easy-install.md
manifests/charts/dash/templates/validatingwebhookconfiguration.yaml
manifests/charts/dash/values.yaml
selenium-testing/package-lock.json
selenium-testing/package.json

Ticket: https://dev.azure.com/intelletive/Minesweeper/_boards/board/t/Minesweeper%20Team/Issues/?workitem=6931
- validating webhook disabled by default
- ingress.hosts defaults to empty array instead of an array containiner 'localhost'
- If validating webhook is enabled, but no hosts are configured, will be treated as if validating webhook is disabled
- Fixde typos 'reguarding' > 'regarding' in docs
- Added validatingwebhook.enabled to table of helm install options

Tweaks for validating webhook & ingress settings in dash chart

---

selenium-testing/test/specs/cluster/images.spec.ts

Added a waitForExist call before trying to use the download button.
This causes Selenium to try to find the button once every second. Once it finds the button, it will continue. If it goes 30s without finding the button, it will fail the test.

Fix Selenium race condition

---

dash/backend/src/modules/kube-hunter/dto/kube-hunter-raw.interface.ts
dash/backend/src/modules/kube-hunter/service/kube-hunter.service.ts
dash/backend/src/modules/security-audit-report/enums/security-audit-report-tools.ts
dash/backend/src/modules/security-audit-report/security-audit.module.ts
dash/backend/src/modules/security-audit-report/services/security-audit-kubehunter.service.ts
dash/backend/src/modules/security-audit-report/services/security-audit-report-pdf-helpers.service.ts
dash/backend/src/modules/security-audit-report/services/security-audit-tool-service.factory.ts
dash/frontend/src/app/core/enum/SecurityAuditReportTools.ts
dash/frontend/src/app/modules/private/pages/reports/security-audit-report/security-audit-report.component.ts

Ticket: 6991
Added kube-hunter as an option for a tool in the Security Audit reports
Has the intro paragraph, and a summary table with this data for each cluster 
- cluster name
- last scanned (N/A if never scanned)
- High*
- Medium*
- Low*
*merged into single cell saying 'no scan run' if no scan has been run
Has the intro paragraph. If kube-hunter has not been run, or had no vulnerabilities, will display an appropriate message.
Otherwise, for each location with at leasst 1 vulnerability it will display a table with this information: (Largely based on the kube hunter reports detail screen from the UI)
- Severity
- Category
- Vulnerability
- Description
- Additional Information (link to avd.aquasec.com page for the vulnerability, should be clickable link if your pdf viewer supports that)

Kube hunter section can now be used for security audit reports

---

dash/backend/src/modules/kube-bench/dto/kube-bench-dto.ts
dash/backend/src/modules/security-audit-report/enums/security-audit-report-tools.ts
dash/backend/src/modules/security-audit-report/security-audit.module.ts
dash/backend/src/modules/security-audit-report/services/security-audit-kube-bench.service.ts
dash/backend/src/modules/security-audit-report/services/security-audit-kubehunter.service.ts
dash/backend/src/modules/security-audit-report/services/security-audit-report-pdf-helpers.service.ts
dash/backend/src/modules/security-audit-report/services/security-audit-tool-service.factory.ts
dash/frontend/src/app/core/enum/SecurityAuditReportTools.ts
dash/frontend/src/app/modules/private/pages/reports/security-audit-report/security-audit-report.component.ts

Ticket 6990
Adds kube-bench as a tool that can be included in security audit reports. When enabled, the information below will be added to the summary section & cluster details sections for the tool
In the summary section it has the intro paragraph followed by a table with a quick summary for all clusters
Fields in the summary table:
- cluster name
- Last scanned (N/A if never scanned)
- Passed*
- Failed*
- Warnings*
*These cells are merged to display 'No scan run' if never scanned
The data contained for each cluster is formatted with a header for each section (ex.  
'3. Control Plane Configuration (cis-1.7 v1.27)'). These sections appear under the main kube bench header for the cluster in the table of contents.
Within each section, a table for each test is present, containing a list of …

Security audit kube bench report

---

dash/backend/src/main.ts

Ticket 6926
content was undefined on all of the get requests, since get requests don't have request bodies.

Fix errors generating swagger allowed schemas

---

dash/backend/src/modules/reports/controllers/reports-download.controller.ts

How to Duplicate:
1. Log in to dev-m9sweeper as a read-only user
2. Open dev tools to the network tab, clear existing entries
3. Open the Falco page: https://dev-m9sweeper.intelletive.com/private/clusters/39/reports/security-audit-report
In the "Recent Events" card, click the "Download" button
"Report could not be generated" will display at the bottom of the page

Fix Read Only Users Can Not Download Audit Report
