m9sweeper/m9sweeper

dash/frontend/src/app/modules/private/pages/falco/falco-dialog/falco-dialog.component.html
docs/content/en/docs/Concepts/Falco/_index.md
docs/content/en/docs/Getting started/advanced-install.md
manifests/charts/dash/templates/dash-falco.yaml
manifests/charts/dash/templates/ingress.yaml
manifests/charts/dash/templates/servicemonitor.yaml
manifests/charts/dash/values.yaml

Tested and confirmed this is routing to dash-falco

Falco bulkhead

---

dash/frontend/src/app/modules/private/pages/cluster/kube-bench/kube-bench-dialog/kube-bench-dialog.component.scss
tests/selenium/test/test/TestGateKeeper.java
tests/selenium/test/test/TestKubeBench.java

Switches the Gatekeeper test back to utilizing helm for installation and adds the `helm repo update` command to fix that install process. Also fixes the Kube Bench test by updating the name of the environment it looks for.

Fix automated tests

---

dash/backend/src/modules/docker-registries/services/docker-registries.service.ts

map never actually returned, this should fix it

Fix sensitive info trimming

---

dash/backend/src/cron-jobs/m9sweeper_cron_jobs.service.ts
dash/backend/src/modules/auth/services/ldap/generic-ldap.service.ts

- Restored cron service
- Added constructor & injected logger into ldap service

Fix build issues

---

dash/frontend/src/app/modules/private/pages/docker-registries/docker-registries-create/docker-registries-create.component.ts
trawler/src/main/java/io/m9sweeper/trawler/scanners/Trivy.java

- Changes to Angular Forms caused docker alias input to error out, fixes
- Removed unnecessay  single quotes from escaped environment variables in trivy commands from Trawler, which caused problems for linux. Removed those quotes

Fix Trawler related issues

---

dash/backend/src/modules/namespace/dao/namespace.dao.ts
dash/frontend/src/app/core/services/namespace.service.ts
dash/frontend/src/app/modules/private/pages/cluster/add-cluster-wizard/add-cluster-wizard.component.html
dash/frontend/src/app/modules/private/pages/cluster/cluster-details/cluster-details.component.html
dash/frontend/src/app/modules/private/pages/cluster/gate-keeper-install-wizard-dialog/gate-keeper-install-wizard-dialog.component.html
dash/frontend/src/app/modules/private/pages/cluster/kube-bench/kube-bench-dialog/kube-bench-dialog.component.html
dash/frontend/src/app/modules/private/pages/cluster/kube-hunter/kube-hunter-dialog/kube-hunter-dialog.component.html
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-namespaces/kubernetes-namespaces.component.html
dash/frontend/src/app/modules/private/pages/cluster/service-account-wizard/service-account-wizard.component.html
dash/frontend/src/app/modules/private/pages/cluster/service-account-wizard/service-account-wizard.component.scss
dash/frontend/src/app/modules/private/pages/falco/falco-dialog/falco-dialog.component.html
dash/frontend/src/styles.scss

- Removed labels from data rows of namespace table on workloads page
- Several code blocks were very skinny, made them wider
- Several tweaks to add cluster wizard
- Gave one copy to clipboard button a bigger space so it didn't put its text on multiple lines
-  Updated text in manual service account flow to be more accurate. It looks like someone refactored it to use only 1 command to get the token, but didn't change the text referencing multiple commands
- Used global version of some utility css classes, moved others to global stylesheet
- Moved Falco Dialog (i) as a suffix to the input it was related to, restored its functionality as a link, and made it open in a new tab
The list namespaces endpoint was slightly updated to make it work more correctly
1. Use coalesce to treat namespaces …

More Angular follow up fixes

---

dash/frontend/src/app/app.component.ts
dash/frontend/src/app/app.module.ts
dash/frontend/src/app/core/interceptors/http-jwt-interceptor.ts
dash/frontend/src/app/modules/private/menus/menu.component.ts
dash/frontend/src/app/modules/private/pages/cluster/gate-keeper-install-wizard-dialog/gate-keeper-install-wizard-dialog.component.ts
dash/frontend/src/app/modules/private/pages/cluster/kube-bench/kube-bench-dialog/kube-bench-dialog.component.ts
dash/frontend/src/app/modules/private/pages/cluster/kube-hunter/kube-hunter.component.ts
dash/frontend/src/app/modules/private/pages/falco/falco-dialog/falco-dialog.component.ts
dash/frontend/src/app/modules/private/pages/falco/falco-events-list/falco-events-list.component.ts
dash/frontend/src/app/modules/private/pages/image/image-scan-result-scanner-details/image-scan-result-scanner-details.component.ts
dash/frontend/src/app/modules/public/pages/login/login.component.ts

Basically, .unsubscribe() was being called on a behavior subject, which caused a race condition between that and the subscriptions to those behavior subjects that could cause the subscription to be unsubscribed twice (Which throws the error)
- Removed a bunch of unused imports & variables from linter suggestions on pages I touched
- Refactored a few observables to close using a .unsubscribe$ pattern while I figured out which observable was the issue

Rxjs error (+linting)

---

dash/frontend/src/app/app.module.ts
dash/frontend/src/app/modules/private/menus/menu.component.html
dash/frontend/src/app/modules/private/menus/services/cluster-info-menu.service.ts
dash/frontend/src/app/modules/private/pages/cluster/cluster-details/cluster-details.component.ts
dash/frontend/src/app/modules/private/pages/dashboard/dashboard.component.ts
dash/frontend/src/app/modules/shared/shared.module.ts
dash/frontend/src/app/modules/shared/side-nav/side-nav.component.html
dash/frontend/src/app/modules/shared/side-nav/side-nav.component.ts

- isHandsetOrXS functionality improved
- menu collapsing on "regular" screens
- component triggers working

sidenav bug fixes

---

dash/frontend/src/app/modules/private/pages/cluster/cluster-list/cluster-list.component.html
dash/frontend/src/app/modules/private/pages/cluster/cluster-list/cluster-list.component.scss
dash/frontend/src/styles.scss

- Cluster Cards now look better
- Added some typography theming to improve fonts
- clean up some unneeded styles
- Pleased the linter

Clean up to cluster cards, general typography improvements

---

dash/backend/src/modules/falco/dao/falco.dao.ts
dash/frontend/src/app/modules/private/pages/cluster/cluster-list/cluster-list.component.ts
dash/frontend/src/app/modules/private/pages/cluster/cluster-summary/cluster-summary.component.ts

- Frontend: Remove unused code
- Backend: get falco.dao.buildFalcoLogQuery working

Bug Fixes 3b

---

dash/frontend/src/app/modules/private/pages/cluster/kubernetes-pod-details/kubernetes-pod-details.component.html
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-pod-details/kubernetes-pod-details.component.scss
dash/frontend/src/app/modules/private/pages/cluster/kubesec/kubesec.component.scss
dash/frontend/src/styles.scss

Fixed Header, button sizes, spacing above table look a bit weird issue

Refactor CSS for Kubernetes Pods Details Page

---

dash/frontend/src/app/modules/private/pages/policies/policy-list/policy-list.component.html
dash/frontend/src/app/modules/private/pages/policies/policy-list/policy-list.component.scss

- bug fix for the policy page
- format policy page table so scrolling works properly on small screens

Policy Page Bug Fix

---

dash/frontend/src/app/modules/private/pages/cluster/cluster-summary/cluster-summary.component.html
dash/frontend/src/app/modules/private/pages/cluster/cluster-summary/cluster-summary.component.scss
dash/frontend/src/app/modules/shared/alert-dialog/alert-dialog.component.html
dash/frontend/src/styles.scss

formatting fix for the table on the cluster summary page

---

dash/backend/src/modules/user/dao/user.dao.ts
dash/frontend/src/app/modules/private/pages/api-key-management/api-key-form/api-key-form.component.html
dash/frontend/src/app/modules/private/pages/api-key-management/api-key-form/api-key-form.component.ts
dash/frontend/src/app/modules/private/pages/api-key-management/api-key-list/api-key-list.component.html
dash/frontend/src/app/modules/private/pages/policies/policy-create/policy-create.component.html
dash/frontend/src/app/modules/shared/components/copy-to-clipboard-button/copy-to-clipboard-button.component.html
dash/frontend/src/app/modules/shared/components/copy-to-clipboard-button/copy-to-clipboard-button.component.ts
dash/frontend/src/app/modules/shared/components/hideable-text/hideable-text.component.html
dash/frontend/src/app/modules/shared/components/hideable-text/hideable-text.component.ts
dash/frontend/src/app/modules/shared/shared.module.ts

- Rewrote get user query in DAO so that pagination/sorting works as expected (See comment in code for details)
- API Key page can now hide/show & copy api keys
- API key form
- button now blue
- use margin instead of nbsp for spacing
- clean up subscriptins    
- scanner table now labeled with actions instead of elipsis in policy form

More ng followup

---

dash/frontend/src/app/modules/private/pages/cluster/kube-bench/kube-bench-dialog/kube-bench-dialog.component.html
dash/frontend/src/app/modules/private/pages/cluster/kube-hunter/kube-hunter-dialog/kube-hunter-dialog.component.html

These got rolled back to the old repo URL at some point.

Fix helm repo URL in KB and KH

---

selenium-testing/package.json
selenium-testing/test/config.ts
selenium-testing/test/functions/logout.ts
selenium-testing/test/specs/cluster/gatekeeper.spec.ts
selenium-testing/test/specs/cluster/images.spec.ts
selenium-testing/test/specs/cluster/kube-bench.spec.ts
selenium-testing/test/specs/cluster/kube-hunter.spec.ts
selenium-testing/test/specs/cluster/kube-sec.spec.ts
selenium-testing/test/specs/smoke/navigation.spec.ts
selenium-testing/wdio.shared.conf.ts

Updates all tests to work with the latest m9sweeper code as of this evening.

Update selenium tests

---

dash/frontend/src/app/core/services/pod.service.ts
dash/frontend/src/app/modules/private/pages/cluster/cluster-list/cluster-list.component.scss
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-namespaces/kubernetes-namespaces.component.html
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-namespaces/kubernetes-namespaces.component.scss
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-namespaces/kubernetes-namespaces.component.ts
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-pod-details/kubernetes-pod-details.component.html
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-pod-details/kubernetes-pod-details.component.scss
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-pod-details/kubernetes-pod-details.component.ts
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-pods/kubernetes-pods.component.html
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-pods/kubernetes-pods.component.scss
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-pods/kubernetes-pods.component.ts
dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.scss
dash/frontend/src/app/modules/shared/datepicker-component/datepicker.component.html
dash/frontend/src/app/modules/shared/datepicker-component/datepicker.component.ts

- cluster group dashboard: improve spacing
- datepicker:
- option to prevent future dates
- remove initalDate (wasn't working)
- bind date to input
- fix initial date setting
- various locations in workloads:
- make each row <a> tags
- prevent future date selection
- pods in namespaces:
- use mat-card
-  fix small screen format
- pod service: document a method
- pod details: fix formatting
- image scan details: display full image name

Workloads Pages

---

dash/backend/src/modules/user/controllers/user.controller.ts
dash/backend/src/modules/user/dao/user.dao.ts
dash/frontend/src/app/modules/private/menus/services/settings-menu.service.ts
dash/frontend/src/app/modules/private/pages/api-key-management/api-key-list/api-key-list.component.html
dash/frontend/src/app/modules/private/pages/app-settings/app-settings.component.html
dash/frontend/src/app/modules/private/pages/docker-registries/docker-registries-list/docker-registries-list.component.html
dash/frontend/src/app/modules/private/pages/exceptions/exception-list/exception-list.component.html
dash/frontend/src/app/modules/private/pages/external-auth-configuration/external-auth-configuration-list/external-auth-configuration-list.component.html
dash/frontend/src/app/modules/private/pages/external-auth-configuration/external-auth-configuration-list/external-auth-configuration-list.component.ts
dash/frontend/src/app/modules/private/pages/falco/falco-json-data-dialog/falco-json-data-dialog.component.html
dash/frontend/src/app/modules/private/pages/falco/falco-json-data-dialog/falco-json-data-dialog.component.scss
dash/frontend/src/app/modules/private/pages/policies/policy-create/policy-create.component.html
dash/frontend/src/app/modules/private/pages/policies/policy-create/policy-create.component.scss
dash/frontend/src/app/modules/private/pages/policies/policy-list/policy-list.component.html
dash/frontend/src/app/modules/private/pages/user/create-user-form/create-user.component.html
dash/frontend/src/app/modules/private/pages/user/create-user-form/create-user.component.scss
dash/frontend/src/app/modules/private/pages/user/create-user-form/create-user.component.ts
dash/frontend/src/app/modules/private/pages/user/update-user-profile/update-user-profile.component.html
dash/frontend/src/app/modules/private/pages/user/update-user-profile/update-user-profile.component.ts
dash/frontend/src/app/modules/private/pages/user/user-list/user-list.component.html
dash/frontend/src/app/modules/private/pages/user/user-list/user-list.component.ts
dash/frontend/src/app/modules/private/private-routing.module.ts
dash/frontend/src/app/modules/shared/directives/phone-mask.directive.ts
dash/frontend/src/app/modules/shared/directives/usa-phone-mask.directive.ts
dash/frontend/src/app/modules/shared/shared.module.ts
dash/frontend/src/app/modules/shared/subnavigation/sub-navigation.component.html
dash/frontend/src/app/modules/shared/subnavigation/sub-navigation.component.scss
dash/frontend/src/app/modules/shared/subnavigation/sub-navigation.component.theme.scss
dash/frontend/src/app/modules/shared/subnavigation/sub-navigation.component.ts

- Add phone number mask directive for inputs
- Fix sorting for list of users
- Clean up scanner list on create/edit policy page
- Clean up Settings pages header

User List cleanup

---

dash/frontend/src/app/modules/private/menus/menu.component.html
dash/frontend/src/app/modules/private/menus/menu.component.ts
dash/frontend/src/app/modules/private/menus/services/cluster-info-menu.service.ts
dash/frontend/src/app/modules/private/menus/services/cluster-list-menu.service.ts
dash/frontend/src/app/modules/private/menus/services/nav-service.interface.ts
dash/frontend/src/app/modules/private/menus/services/settings-menu.service.ts
dash/frontend/src/app/modules/shared/side-nav/side-nav.component.html
dash/frontend/src/app/modules/shared/side-nav/side-nav.component.ts

+ cluster list button to left nav

---

dash/frontend/src/app/modules/private/pages/cluster/cluster-list/cluster-list.component.html
dash/frontend/src/generic-styles.scss

- scss mixin that generates classes from defined properties
- dashboard buttons use scss classes to make them look nice on all screen sizes

SCSS Mixin

---

dash/frontend/src/app/core/enum/Authority.ts
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-namespaces/kubernetes-namespaces.component.html
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-namespaces/kubernetes-namespaces.component.scss
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-pod-details/kubernetes-pod-details.component.html
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-pods/kubernetes-pods.component.html
dash/frontend/src/app/modules/private/pages/cluster/kubernetes-pods/kubernetes-pods.component.ts
dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.html
dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.scss
dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.ts
dash/frontend/src/app/modules/private/pages/image/images-list/image.component.html
dash/frontend/src/app/modules/private/pages/image/images-list/image.component.scss
dash/frontend/src/generic-styles.scss

- added align-items & justify-content to the generic styles
- images header page looks nicer
- images stylesheet cleaned up
- images table has tooltip on "name and tag" field
- image scan details page cleaned up
- clean up some of the workload pages

+ generic classes; various page cleanups

---

selenium-testing/.run/test_all.run.xml
selenium-testing/.run/test_cluster.run.xml
selenium-testing/.run/test_organization.run.xml
selenium-testing/.run/test_smoke.run.xml
selenium-testing/.run/test_user.run.xml
selenium-testing/test/functions/download.ts
selenium-testing/test/functions/login.ts
selenium-testing/test/functions/logout.ts
selenium-testing/test/specs/cluster/gatekeeper.spec.ts
selenium-testing/test/specs/cluster/images.spec.ts
selenium-testing/test/specs/cluster/kube-bench.spec.ts
selenium-testing/test/specs/cluster/kube-hunter.spec.ts
selenium-testing/test/specs/cluster/kubesec.spec.ts
selenium-testing/test/specs/smoke/login-logout.spec.ts
selenium-testing/test/specs/smoke/navigation.spec.ts
selenium-testing/wdio.shared.conf.ts

* Updates all the tests to work with the latest m9sweeper code.
* Fixes spelling mistakes
* Fixes grammar mistakes
* Supresses errors about unknown functions for the `customClick()` and `customScreenshot()` and other custom functions we have created.
* Replaces the `download()` function with the `downloadAndVerify()` which properly handles regular expressions for filenames in addition to static file names. It also greatly simplifies that function.

Fix tests and cleanup spelling and grammar

---

dash/backend/package-lock.json
dash/backend/package.json
dash/backend/vendor/nestjs-mailer/package-lock.json
dash/backend/vendor/nestjs-mailer/package.json

Also removed from vendor package (npm rm also decided to alphabetize the imports when I ran npm rm is the reason for the other chagnes in that file.)

remove rimraf package

---

dash/backend/src/modules/auth/controllers/non-redirectable-login.controller.ts
dash/frontend/src/app/modules/private/menus/services/cluster-info-menu.service.ts
docker-compose/README.md
docs/content/en/docs/Concepts/Gatekeeper/getting-started.md
docs/content/en/docs/Concepts/Gatekeeper/reviewing-exceptions.md
docs/content/en/docs/Concepts/KubeSec/_index.md
docs/content/en/docs/Reference/dash-parameters.md
selenium-testing/README.md
selenium-testing/test/specs/cluster/kube-bench.spec.ts
selenium-testing/test/specs/cluster/kube-hunter.spec.ts
selenium-testing/test/specs/smoke/navigation.spec.ts

Fix some names to ensure that all of these things are named & cased correctly
- Gatekeeper
- Kubesec
- kube-bench
- kube-hunter
Finishes up ticket 6780

fix some names

---

dash/frontend/src/app/modules/private/pages/cluster/service-account-wizard/service-account-wizard.component.html
dash/frontend/src/app/modules/private/pages/cluster/service-account-wizard/service-account-wizard.component.scss
dash/frontend/src/app/modules/private/pages/falco/falco-dialog/falco-dialog.component.html
dash/frontend/src/app/modules/private/pages/falco/falco-dialog/falco-dialog.component.scss
dash/frontend/src/app/modules/private/pages/falco/falco-events-list/falco-events-list.component.ts
dash/frontend/src/styles.scss

- Falco dialog wider
- Code snippets no longer line wrap
- Code snippets now horizontally scroll when needed
- Fixed height of get secret command textarea in service account modal

Install dialog UI tweaks

---

dash/frontend/src/app/modules/private/pages/cluster/add-cluster-wizard/add-cluster-wizard.component.html
dash/frontend/src/app/modules/private/pages/cluster/add-cluster-wizard/add-cluster-wizard.component.ts
dash/frontend/src/app/modules/private/pages/reports/worst-images/worst-images.component.html
dash/frontend/src/app/modules/private/pages/reports/worst-images/worst-images.component.ts

Changed the label for iamges with no CVEs from 'None' to 'No CVEss' and editted the helper text to account for this
- Now converts to vertical stepper rather than horizontal stepper for small screens (<=600px).
- Labelled manual enforcement webhook enforcement command
- Cleaned up observeables

worst vulnerability & add clsuter wizard tweaks

---

manifests/charts/kube-bench/templates/cronjob-ack.yaml
manifests/charts/kube-bench/templates/cronjob-aks.yaml
manifests/charts/kube-bench/templates/cronjob-eks-asff.yaml
manifests/charts/kube-bench/templates/cronjob-eks.yaml
manifests/charts/kube-bench/templates/cronjob-gke.yaml
manifests/charts/kube-bench/templates/cronjob-master.yaml
manifests/charts/kube-bench/templates/cronjob-node.yaml
manifests/charts/kube-bench/templates/cronjob.yaml
manifests/charts/kube-bench/templates/job-ack.yaml
manifests/charts/kube-bench/templates/job-aks.yaml
manifests/charts/kube-bench/templates/job-eks-asff.yaml
manifests/charts/kube-bench/templates/job-eks.yaml
manifests/charts/kube-bench/templates/job-gke.yaml
manifests/charts/kube-bench/templates/job-master.yaml
manifests/charts/kube-bench/templates/job-node.yaml
manifests/charts/kube-bench/templates/job.yaml
manifests/charts/kube-bench/values.yaml

Ticket 6826
There were 2 issues that were preventing kube-bench from working properly anywhere, and 1 for 1 specific mode
Per the first parapgraph in their [kube-bench how to run guide](https://aquasecurity.github.io/kube-bench/dev/running/), to run kube-bench you will probably have to run as root in order to read config files. (The pods run the kube-bench CLI).
We have a helm chart that basically is a tweaked version of the job kube-bench provides with a few extra features. One of those additions is a security context causing the pod to run as non-root as user 1000.
Disabled the security context by default
By looking at the git history, it looks like we started using the official kube-bench image instead of one from a m9sweeper registry in February 2023. Due to this (I assume), curl was …

Kube bench fixes

---

dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.html
dash/frontend/src/app/modules/private/pages/image/image-scan-result/image-scan-result.component.ts

- hid certain buttons on print
- removed a full column on print (its button is hidden)

Prettify the Image Scan Results Print Page

---

dash/backend/src/modules/reports/dao/reports.dao.ts

WAs using wrong alias to access table.

Fix 500 error thrown on vulnerability export page

---

dash/backend/src/modules/pod/dao/pod.dao.ts

Ticket: https://dev.azure.com/intelletive/Minesweeper/_boards/board/t/Minesweeper%20Team/Issues/?workitem=6925
Previously calculated which images were new to the pod, and added those links.
Now as a transaction clears all links, and then recreates with the current data.

now resets pod links when syncing
